# fly.toml app configuration file generated for yandaoyqchatbot-withered-snowflake-335 on 2025-07-09T14:35:30+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yandaoyqchatbot-withered-snowflake-335'
primary_region = 'sin'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
